version: '3.2'
services:
    nextcloud-db:
        image: postgres
        restart: unless-stopped
        volumes:
         - ${CONTAINERP}/nextcloud-db:/var/lib/postgresql/data
        environment:
         - POSTGRES_DB_FILE=/run/secrets/postgres_db
         - POSTGRES_USER_FILE=/run/secrets/postgres_user
         - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
         - postgres_db
         - postgres_password
         - postgres_user
        networks:
         - back-nextcloud
    nextcloud:
        restart: unless-stopped
        image: nextcloud
        volumes:
         - ${CONTAINERP}/nextcloud/nextcloud:/var/www/html
         - ${CONTAINERP}/nextcloud/apps:/var/www/html/custom_apps
         - ${CONTAINERP}/nextcloud/config:/var/www/html/config
         - ${CONTAINERP}/nextcloud/data:/var/www/html/data
        environment:
          - POSTGRES_HOST=nextcloud-db
          - POSTGRES_DB_FILE=/run/secrets/postgres_db
          - POSTGRES_USER_FILE=/run/secrets/postgres_user
          - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
#          - NEXTCLOUD_ADMIN_PASSWORD=pwd # REQUIRED?
#          - NEXTCLOUD_ADMIN_USER=admin
        secrets:
         - postgres_db
         - postgres_password
         - postgres_user
        ports:
         - 8080:80
        networks:
         - front
         - back-nextcloud
        depends_on:
         - nextcloud-db
networks:
    front:
    back-nextcloud:
secrets:
  postgres_db:
    file: ./secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./secrets/postgres_user.txt # put postgresql username to this file
